[0m09:45:05.423427 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017232320910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017232305ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017232305CD0>]}


============================== 09:45:05.429642 | 25a39a94-62a5-48c3-945d-9d328cdf1b73 ==============================
[0m09:45:05.429642 [info ] [MainThread]: Running with dbt=1.8.7
[0m09:45:05.430659 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\qwc12\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:45:05.431642 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\qwc12\AppData\Local\Programs\Python\Python311\Scripts\pythonProject1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:45:05.433640 [debug] [MainThread]: Command `dbt run` failed at 09:45:05.433640 after 0.09 seconds
[0m09:45:05.433640 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000172322B1B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017231F1BED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001722B6E9310>]}
[0m09:45:05.434641 [debug] [MainThread]: Flushing usage events
[0m09:45:52.241548 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4FC09D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4F93410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4FA5350>]}


============================== 09:45:52.246730 | 1df87af6-4b21-4c23-b90c-80d2c1213914 ==============================
[0m09:45:52.246730 [info ] [MainThread]: Running with dbt=1.8.7
[0m09:45:52.247732 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\qwc12\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\qwc12\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pythonProject1\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:45:52.248733 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt cannot run because no profile was specified for this dbt project.
  To specify a profile for this project, add a line like the this to
  your dbt_project.yml file:
  
  profile: [profile name]
  
  Here, [profile name] should be replaced with a profile name
  defined in your profiles.yml file. You can find profiles.yml here:
  
  C:\Users\qwc12\.dbt/profiles.yml
  
[0m09:45:52.252731 [debug] [MainThread]: Command `dbt run` failed at 09:45:52.251731 after 0.10 seconds
[0m09:45:52.252731 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4F47790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4FC18D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAE4FC32D0>]}
[0m09:45:52.253730 [debug] [MainThread]: Flushing usage events
[0m10:31:04.954756 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697F15090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697F14250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697F14890>]}


============================== 10:31:04.958752 | 2c4b3eea-4de2-4414-9608-e2d92b97a911 ==============================
[0m10:31:04.958752 [info ] [MainThread]: Running with dbt=1.8.7
[0m10:31:04.959753 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\qwc12\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\pythonProject1\\logs', 'profiles_dir': 'C:\\Users\\qwc12\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt build', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:31:04.961752 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt cannot run because no profile was specified for this dbt project.
  To specify a profile for this project, add a line like the this to
  your dbt_project.yml file:
  
  profile: [profile name]
  
  Here, [profile name] should be replaced with a profile name
  defined in your profiles.yml file. You can find profiles.yml here:
  
  C:\Users\qwc12\.dbt/profiles.yml
  
[0m10:31:04.963753 [debug] [MainThread]: Command `dbt build` failed at 10:31:04.962753 after 0.10 seconds
[0m10:31:04.963753 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697F0F650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697EB5210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A697F15290>]}
[0m10:31:04.964753 [debug] [MainThread]: Flushing usage events
